// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/castorworks/castor/internal/application/service"
	"github.com/castorworks/castor/internal/infrastructure/cache"
	"github.com/castorworks/castor/internal/infrastructure/database"
	"github.com/castorworks/castor/internal/infrastructure/external"
	"github.com/castorworks/castor/internal/infrastructure/i18n"
	"github.com/castorworks/castor/internal/infrastructure/persistence"
	"github.com/castorworks/castor/internal/infrastructure/storage"
	"github.com/castorworks/castor/internal/interfaces/api"
	"github.com/castorworks/castor/internal/interfaces/api/handler"
	"github.com/castorworks/castor/internal/interfaces/api/middleware"
	"github.com/castorworks/castor/internal/interfaces/api/server"
	"github.com/castorworks/castor/internal/pkg/ratelimit"
)

// Injectors from wire.go:

func InitServer() (*server.Server, error) {
	engine, err := server.NewGinEngine()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgres()
	if err != nil {
		return nil, err
	}
	repository := persistence.NewMenuRepository(db)
	resourceRepository := persistence.NewResourceRepository(db)
	menuService := service.NewMenuService(repository, resourceRepository)
	authorizationRepository := persistence.NewAuthorizationRepository(db)
	roleRepository := persistence.NewRoleRepository(db)
	userRepository := persistence.NewUserRepository(db)
	rbacService := service.NewRBACService(authorizationRepository, roleRepository, resourceRepository, userRepository)
	audit_logRepository := persistence.NewAuditLogRepository(db)
	auditLogService := service.NewAuditLogService(audit_logRepository)
	menuHandler := handler.NewMenuHandler(menuService, rbacService, auditLogService)
	s3Client, err := storage.NewS3()
	if err != nil {
		return nil, err
	}
	assetRepository := persistence.NewAssetRepository(db)
	assetPolicy := provideAssetPolicy()
	assetService := service.NewAssetService(s3Client, assetRepository, assetPolicy)
	notificationRepository := persistence.NewNotificationRepository(db)
	userNotificationRepository := persistence.NewUserNotificationRepository(db)
	notificationService := service.NewNotificationService(notificationRepository, userNotificationRepository)
	templateRenderer, err := i18n.NewNotificationTemplateRenderer()
	if err != nil {
		return nil, err
	}
	notificationPublisher := service.NewNotificationPublisher(notificationService, templateRenderer)
	adminAssetHandler := handler.NewAdminAssetHandler(assetService, notificationPublisher)
	adminAuditLogHandler := handler.NewAdminAuditLogHandler(auditLogService)
	permissionService := service.NewPermissionService(resourceRepository, roleRepository, authorizationRepository)
	adminAuthorizationHandler := handler.NewAdminAuthorizationHandler(permissionService, menuService, rbacService, auditLogService)
	settingRepository := persistence.NewSettingRepository(db)
	settingHelper := service.NewSettingHelper(settingRepository)
	universalClient, err := cache.NewRedis()
	if err != nil {
		return nil, err
	}
	rsaKeyConfig := provideRsaKeyConfig()
	rsaService := service.NewRsaService(universalClient, rsaKeyConfig)
	userService := service.NewUserService(userRepository, settingHelper, rsaService, rbacService)
	login_historyRepository := persistence.NewLoginHistoryRepository(db)
	loginHistoryService := service.NewLoginHistoryService(login_historyRepository)
	adminDashboardHandler := handler.NewAdminDashboardHandler(userService, assetService, loginHistoryService, auditLogService)
	dictTypeRepository := persistence.NewDictTypeRepository(db)
	dictItemRepository := persistence.NewDictItemRepository(db)
	dictionaryService := service.NewDictionaryService(dictTypeRepository, dictItemRepository)
	adminDictionaryHandler := handler.NewAdminDictionaryHandler(dictionaryService)
	adminLoginHistoryHandler := handler.NewAdminLoginHistoryHandler(loginHistoryService)
	adminNotificationHandler := handler.NewAdminNotificationHandler(notificationService, auditLogService)
	settingService := service.NewSettingService(settingRepository)
	adminSettingHandler := handler.NewAdminSettingHandler(settingService)
	adminUserHandler := handler.NewAdminUserHandler(userService, auditLogService, notificationPublisher)
	adminHandlers := &api.AdminHandlers{
		Menu:          menuHandler,
		Asset:         adminAssetHandler,
		AuditLog:      adminAuditLogHandler,
		Authorization: adminAuthorizationHandler,
		Dashboard:     adminDashboardHandler,
		Dictionary:    adminDictionaryHandler,
		LoginHistory:  adminLoginHistoryHandler,
		Notification:  adminNotificationHandler,
		Setting:       adminSettingHandler,
		User:          adminUserHandler,
	}
	verificationCodeStore := external.NewVerificationCodeStore(universalClient)
	accountService := service.NewAccountService(userRepository, verificationCodeStore, rsaService, rbacService)
	userAvatarService := service.NewUserAvatarService(s3Client)
	accountHandler := handler.NewAccountHandler(userService, accountService, userAvatarService, auditLogService)
	accountPermissionHandler := handler.NewAccountPermissionHandler(rbacService)
	assetHandler := handler.NewAssetHandler(assetService)
	captchaClient := external.NewCaptchaClient(universalClient)
	rateLimiter := ratelimit.NewRateLimiter(universalClient)
	sender, err := external.NewAliyunSmsClient()
	if err != nil {
		return nil, err
	}
	client := external.NewMailClient()
	runtimePolicy := provideRuntimePolicy()
	authService := service.NewAuthService(userRepository, settingHelper, captchaClient, rateLimiter, verificationCodeStore, sender, client, rbacService, rsaService, runtimePolicy)
	authenticationHandler := handler.NewAuthenticationHandler(authService, rsaService, auditLogService)
	dictionaryHandler := handler.NewDictionaryHandler(dictionaryService)
	loginHistoryHandler := handler.NewLoginHistoryHandler(loginHistoryService)
	notificationHandler := handler.NewNotificationHandler(notificationService)
	settingHandler := handler.NewSettingHandler(settingService)
	userHandlers := &api.UserHandlers{
		Menu:              menuHandler,
		Account:           accountHandler,
		AccountPermission: accountPermissionHandler,
		Asset:             assetHandler,
		Authentication:    authenticationHandler,
		Dictionary:        dictionaryHandler,
		LoginHistory:      loginHistoryHandler,
		Notification:      notificationHandler,
		Setting:           settingHandler,
	}
	loginService := service.NewLoginService(userService, userRepository, loginHistoryService, rateLimiter, captchaClient, verificationCodeStore, rsaService, authService, auditLogService, settingService, runtimePolicy)
	tokenBlacklistService := service.NewTokenBlacklistService(universalClient)
	jwtMiddleware, err := middleware.NewJwtMiddleware(loginService, rbacService, tokenBlacklistService, auditLogService)
	if err != nil {
		return nil, err
	}
	adminRoleMiddleware := middleware.NewAdminRoleMiddleware(rbacService)
	router := api.NewRouter(adminHandlers, userHandlers, jwtMiddleware, adminRoleMiddleware, rateLimiter, db, universalClient)
	serverServer := server.NewServer(engine, router, auditLogService, db, universalClient)
	return serverServer, nil
}
