// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/castorworks/castor/internal/application/service"
	"github.com/castorworks/castor/internal/infrastructure/cache"
	"github.com/castorworks/castor/internal/infrastructure/database"
	"github.com/castorworks/castor/internal/infrastructure/external"
	"github.com/castorworks/castor/internal/infrastructure/i18n"
	"github.com/castorworks/castor/internal/infrastructure/persistence"
	"github.com/castorworks/castor/internal/infrastructure/storage"
	"github.com/castorworks/castor/internal/interfaces/api"
	"github.com/castorworks/castor/internal/interfaces/api/handler"
	"github.com/castorworks/castor/internal/interfaces/api/middleware"
	"github.com/castorworks/castor/internal/interfaces/api/server"
	"github.com/castorworks/castor/internal/pkg/ratelimit"
)

// Injectors from wire.go:

func InitServer() (*server.Server, error) {
	engine, err := server.NewGinEngine()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgres()
	if err != nil {
		return nil, err
	}
	repository := persistence.NewMenuRepository(db)
	resourceRepository := persistence.NewResourceRepository(db)
	menuService := service.NewMenuService(repository, resourceRepository)
	authorizationRepository := persistence.NewAuthorizationRepository(db)
	roleRepository := persistence.NewRoleRepository(db)
	userRepository := persistence.NewUserRepository(db)
	departmentRepository := persistence.NewDepartmentRepository(db)
	rbacService := service.NewRBACService(authorizationRepository, roleRepository, resourceRepository, userRepository, departmentRepository)
	audit_logRepository := persistence.NewAuditLogRepository(db)
	auditLogService := service.NewAuditLogService(audit_logRepository)
	menuHandler := handler.NewMenuHandler(menuService, rbacService, auditLogService)
	client, err := storage.NewS3()
	if err != nil {
		return nil, err
	}
	assetStorage := storage.NewAssetStorage(client)
	assetRepository := persistence.NewAssetRepository(db)
	assetPolicy := provideAssetPolicy()
	assetService := service.NewAssetService(assetStorage, assetRepository, assetPolicy, auditLogService)
	notificationRepository := persistence.NewNotificationRepository(db)
	userNotificationRepository := persistence.NewUserNotificationRepository(db)
	namespace := cache.NewNamespace()
	universalClient, err := cache.NewRedis(namespace, db)
	if err != nil {
		return nil, err
	}
	notificationStream := service.NewNotificationStream(universalClient, namespace)
	emailRepository := persistence.NewNotificationEmailRepository(db)
	smtpmailClient, err := external.NewMailClient()
	if err != nil {
		return nil, err
	}
	templateRenderer, err := i18n.NewNotificationTemplateRenderer()
	if err != nil {
		return nil, err
	}
	notificationMailPolicy := provideNotificationMailPolicy()
	notificationEmailService := service.NewNotificationEmailService(emailRepository, smtpmailClient, templateRenderer, notificationMailPolicy)
	notificationService := service.NewNotificationService(notificationRepository, userNotificationRepository, assetService, notificationStream, notificationEmailService)
	notificationPublisher := service.NewNotificationPublisher(notificationService, templateRenderer)
	adminAssetHandler := handler.NewAdminAssetHandler(assetService, notificationPublisher, auditLogService)
	dictTypeRepository := persistence.NewDictTypeRepository(db)
	dictItemRepository := persistence.NewDictItemRepository(db)
	dictionaryService := service.NewDictionaryService(dictTypeRepository, dictItemRepository, universalClient, namespace)
	adminAuditLogHandler := handler.NewAdminAuditLogHandler(auditLogService, rbacService, dictionaryService)
	permissionService := service.NewPermissionService(resourceRepository, roleRepository, authorizationRepository, departmentRepository)
	settingRepository := persistence.NewSettingRepository(db)
	settingHelper := service.NewSettingHelper(settingRepository)
	rsaKeyConfig := provideRsaKeyConfig()
	rsaService := service.NewRsaService(universalClient, namespace, rsaKeyConfig)
	userService := service.NewUserService(userRepository, settingHelper, rsaService, rbacService, assetService, departmentRepository)
	adminAuthorizationHandler := handler.NewAdminAuthorizationHandler(permissionService, menuService, rbacService, auditLogService, userService)
	login_historyRepository := persistence.NewLoginHistoryRepository(db)
	sessionService := service.NewSessionService(authorizationRepository, rbacService, userRepository)
	dashboardService := service.NewDashboardService(userRepository, login_historyRepository, assetService, auditLogService, sessionService)
	adminDashboardHandler := handler.NewAdminDashboardHandler(dashboardService, rbacService)
	departmentService := service.NewDepartmentService(departmentRepository, userRepository)
	adminDepartmentHandler := handler.NewAdminDepartmentHandler(departmentService, rbacService, auditLogService)
	adminDictionaryHandler := handler.NewAdminDictionaryHandler(dictionaryService, auditLogService)
	jobRepository := persistence.NewJobRepository(db)
	assetSweepPolicy := provideAssetSweepPolicy()
	jobCatalog := service.NewJobCatalog(assetService, assetSweepPolicy, authorizationRepository, notificationEmailService)
	jobService := service.NewJobService(jobRepository, jobCatalog, universalClient, namespace)
	adminJobHandler := handler.NewAdminJobHandler(jobService, auditLogService)
	ssoRepository := persistence.NewSSORepository(db)
	keyring, err := provideKeyring()
	if err != nil {
		return nil, err
	}
	ssoPolicy := provideSSOPolicy()
	ssoService, err := service.NewSSOService(ssoRepository, userRepository, userService, keyring, universalClient, namespace, ssoPolicy)
	if err != nil {
		return nil, err
	}
	adminSSOHandler := handler.NewAdminSSOHandler(ssoService, auditLogService)
	loginHistoryService := service.NewLoginHistoryService(login_historyRepository)
	adminLoginHistoryHandler := handler.NewAdminLoginHistoryHandler(loginHistoryService, auditLogService, rbacService, dictionaryService)
	adminNotificationHandler := handler.NewAdminNotificationHandler(notificationService, assetService, auditLogService)
	adminSessionHandler := handler.NewAdminSessionHandler(sessionService, auditLogService, rbacService)
	settingService := service.NewSettingService(settingRepository)
	adminSettingHandler := handler.NewAdminSettingHandler(settingService, auditLogService)
	mfaRepository := persistence.NewMFARepository(db)
	mfaService, err := service.NewMFAService(mfaRepository, userRepository, settingRepository, rsaService, keyring, universalClient, namespace)
	if err != nil {
		return nil, err
	}
	adminUserHandler := handler.NewAdminUserHandler(userService, auditLogService, notificationPublisher, rbacService, departmentService, dictionaryService, mfaService)
	adminHandlers := &api.AdminHandlers{
		Menu:          menuHandler,
		Asset:         adminAssetHandler,
		AuditLog:      adminAuditLogHandler,
		Authorization: adminAuthorizationHandler,
		Dashboard:     adminDashboardHandler,
		Department:    adminDepartmentHandler,
		Dictionary:    adminDictionaryHandler,
		Job:           adminJobHandler,
		SSO:           adminSSOHandler,
		LoginHistory:  adminLoginHistoryHandler,
		Notification:  adminNotificationHandler,
		Session:       adminSessionHandler,
		Setting:       adminSettingHandler,
		User:          adminUserHandler,
	}
	verificationCodeStore := external.NewVerificationCodeStore(universalClient, namespace)
	rateLimiter := ratelimit.NewRateLimiter(universalClient, namespace)
	sender, err := external.NewAliyunSmsClient()
	if err != nil {
		return nil, err
	}
	runtimePolicy := provideRuntimePolicy()
	accountService := service.NewAccountService(userRepository, verificationCodeStore, rateLimiter, sender, smtpmailClient, runtimePolicy, rsaService, rbacService, settingHelper)
	userAvatarService := service.NewUserAvatarService(assetService, userRepository)
	accountHandler := handler.NewAccountHandler(userService, accountService, userAvatarService, auditLogService)
	accountMFAHandler := handler.NewAccountMFAHandler(mfaService, userService, auditLogService)
	captchaClient, err := external.NewCaptchaClient(universalClient, namespace)
	if err != nil {
		return nil, err
	}
	authService := service.NewAuthService(userRepository, settingHelper, captchaClient, rateLimiter, verificationCodeStore, sender, smtpmailClient, rbacService, rsaService, runtimePolicy)
	loginService := service.NewLoginService(userService, userRepository, loginHistoryService, rateLimiter, captchaClient, verificationCodeStore, rsaService, authService, auditLogService, settingService, accountService, runtimePolicy)
	tokenBlacklistService := service.NewTokenBlacklistService(universalClient, namespace)
	jwtMiddleware, err := middleware.NewJwtMiddleware(loginService, rbacService, tokenBlacklistService, auditLogService, mfaService)
	if err != nil {
		return nil, err
	}
	ssoHandler := handler.NewSSOHandler(ssoService, mfaService, loginService, userService, jwtMiddleware, auditLogService)
	notificationStreamHandler := handler.NewNotificationStreamHandler(notificationStream, notificationService, rbacService)
	accountPermissionHandler := handler.NewAccountPermissionHandler(rbacService, auditLogService)
	assetHandler := handler.NewAssetHandler(assetService, auditLogService)
	authenticationHandler := handler.NewAuthenticationHandler(authService, loginService, rsaService, auditLogService)
	dictionaryHandler := handler.NewDictionaryHandler(dictionaryService)
	loginHistoryHandler := handler.NewLoginHistoryHandler(loginHistoryService)
	notificationHandler := handler.NewNotificationHandler(notificationService, assetService)
	settingHandler := handler.NewSettingHandler(settingService)
	userHandlers := &api.UserHandlers{
		Menu:               menuHandler,
		Account:            accountHandler,
		AccountMFA:         accountMFAHandler,
		SSO:                ssoHandler,
		NotificationStream: notificationStreamHandler,
		AccountPermission:  accountPermissionHandler,
		Asset:              assetHandler,
		Authentication:     authenticationHandler,
		Dictionary:         dictionaryHandler,
		LoginHistory:       loginHistoryHandler,
		Notification:       notificationHandler,
		Setting:            settingHandler,
	}
	adminRoleMiddleware := middleware.NewAdminRoleMiddleware(rbacService)
	router := api.NewRouter(adminHandlers, userHandlers, jwtMiddleware, adminRoleMiddleware, rateLimiter, db, universalClient)
	serverServer := server.NewServer(engine, router, auditLogService, jobService, notificationStream, db, universalClient)
	return serverServer, nil
}
