// ============================================================
// The subset of OpenAPI 3.1 the viewer reads (generated by the backend
// from its route catalog: apps/api/openapi.json).
// ============================================================

export interface Schema {
  $ref?: string;
  type?: string;
  format?: string;
  const?: unknown;
  enum?: unknown[];
  items?: Schema;
  properties?: Record<string, Schema>;
  additionalProperties?: Schema | boolean;
  required?: string[];
  anyOf?: Schema[];
  description?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  contentMediaType?: string;
  contentEncoding?: string;
  default?: unknown;
  example?: unknown;
}

export interface Parameter {
  name: string;
  in: 'path' | 'query' | 'header' | 'cookie';
  required?: boolean;
  description?: string;
  schema?: Schema;
}

export interface MediaType {
  schema?: Schema;
}

export interface Operation {
  tags?: string[];
  summary?: string;
  description?: string;
  operationId?: string;
  security?: Record<string, string[]>[];
  parameters?: Parameter[];
  requestBody?: { required?: boolean; content: Record<string, MediaType> };
  responses?: Record<
    string,
    { description?: string; content?: Record<string, MediaType> } & { $ref?: string }
  >;
}

export interface OpenApiDocument {
  openapi: string;
  info: { title: string; version: string; description?: string };
  tags?: { name: string; description?: string }[];
  paths: Record<string, Record<string, Operation>>;
  components?: { schemas?: Record<string, Schema> };
}

/** One operation flattened for listing. */
export interface OperationEntry {
  method: string;
  path: string;
  operation: Operation;
}
