#!/usr/bin/env python3
"""Castor instances on shared Compose infrastructure (deploy/README.md, "Sharing infrastructure between instances").

Usage:
  compose-instance.py new <instance-id> <http-port>   write deploy/compose/instances/<id>.env
  compose-instance.py provision <env-file>            database + role, bucket + RustFS user (idempotent)
  compose-instance.py backup <env-file>               logical snapshot of one instance
  compose-instance.py list <env-file>
  compose-instance.py restore <env-file> <snapshot> --confirm <id>/<snapshot>
  compose-instance.py status                          every instance: id, port, whether its API runs
  compose-instance.py all <up|pull|rollback|backup> [--keep-going]
                                                      one action on every instance, in id order
`all` stops at the first failing instance so an upgrade never leaves a mix of versions
unnoticed; --keep-going continues and still exits non-zero. Both read the env files in
deploy/compose/instances/ (one per tenant; see "Choosing a tenancy model" in deploy/README.md).
The shared infrastructure is the Compose project described by SHARED_ENV_FILE
(default deploy/compose/.env.shared). Secrets reach containers on stdin, never argv.
Single-quoted shell scripts below run inside Linux containers and expand there.
"""
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys

import _tooling as tooling

# Keep in step with the rustfs-init image in compose.infra.yaml.
RC_IMAGE = 'rustfs/rc:v0.1.36'
INSTANCE_ID_RE = r'[a-z0-9][a-z0-9-]{0,31}'
SECRET_RE = r'[A-Za-z0-9_-]{16,}'
SNAPSHOT_RE = r'snapshot-[0-9]{8}_[0-9]{6}'

PROVISION_SQL = r'''\set ON_ERROR_STOP on
\set db_name '{db_name}'
\set db_user '{db_user}'
\set db_password '{db_password}'
SELECT format('CREATE ROLE %I LOGIN', :'db_user') WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'db_user') \gexec
ALTER ROLE :"db_user" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'db_password';
SELECT format('CREATE DATABASE %I OWNER %I', :'db_name', :'db_user') WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = :'db_name') \gexec
REVOKE ALL ON DATABASE :"db_name" FROM PUBLIC;
'''

# Bucket plus a user limited to object access in it (cannot touch other buckets or change
# bucket policy); rerunning resets the user's secret to the env file value. Every step is
# idempotent. Administrator and instance credentials arrive on stdin, never in argv.
PROVISION_BUCKET = r'''
IFS=" " read -r ROOT_ACCESS ROOT_SECRET
IFS=" " read -r BUCKET ACCESS SECRET
rc alias set admin "http://$1" "$ROOT_ACCESS" "$ROOT_SECRET" >/dev/null
POLICY="castor-bucket-$BUCKET"
cat > "$HOME/policy.json" <<JSON
{"Version":"2012-10-17","Statement":[
{"Effect":"Allow","Action":["s3:GetBucketLocation","s3:ListBucket","s3:ListBucketMultipartUploads"],"Resource":["arn:aws:s3:::$BUCKET"]},
{"Effect":"Allow","Action":["s3:GetObject","s3:PutObject","s3:DeleteObject","s3:AbortMultipartUpload","s3:ListMultipartUploadParts"],"Resource":["arn:aws:s3:::$BUCKET/*"]}]}
JSON
rc bucket create --quiet --ignore-existing "admin/$BUCKET"
rc admin policy create admin/ "$POLICY" "$HOME/policy.json" >/dev/null
rc admin user add admin/ "$ACCESS" "$SECRET" >/dev/null
rc admin policy attach admin/ "$POLICY" --user "$ACCESS" >/dev/null
'''


def compose_dir():
    return tooling.ROOT / 'deploy/compose'


def shared_env_file():
    return Path(os.environ.get('SHARED_ENV_FILE') or compose_dir() / '.env.shared')


def backup_root():
    return Path(os.environ.get('BACKUP_ROOT') or tooling.ROOT / 'deploy/backups') / 'instances'


def new(instance_id, port):
    if not re.fullmatch(INSTANCE_ID_RE, instance_id):
        raise tooling.Failure("instance id: 1-32 lowercase letters, digits or '-'")
    if not re.fullmatch(r'[1-9][0-9]{0,4}', port):
        raise tooling.Failure('http port must be a number')
    shared = shared_env_file()
    if not shared.is_file():
        raise tooling.Failure(f'missing {shared} (copy .env.shared.example first)')
    redis_password = tooling.env_get(shared, 'REDIS_PASSWORD')
    if not redis_password:
        raise tooling.Failure(f'{shared}: REDIS_PASSWORD is empty')
    network = tooling.env_get(shared, 'SHARED_NETWORK') or 'castor-shared'
    target = compose_dir() / 'instances' / f'{instance_id}.env'
    if target.exists():
        raise tooling.Failure(f'{target} already exists')
    target.parent.mkdir(mode=0o700, exist_ok=True)
    sql_id = instance_id.replace('-', '_')
    with tooling.private_file(target) as env:
        env.write(f'''# Castor instance "{instance_id}" on the shared infrastructure. Generated by scripts/compose-instance.py.
PROJECT_NAME=castor-{instance_id}
SHARED_NETWORK={network}
API_IMAGE=castor/castor-api:local
WEB_IMAGE=castor/castor-web:local
HTTP_BIND=127.0.0.1
HTTP_PORT={port}
CASTOR_CORS_ORIGINS=http://localhost:{port}
CASTOR_INSTANCE_ID={instance_id}
CASTOR_JWT_KEY={secrets.token_hex(32)}
CASTOR_RSA_SECRET={secrets.token_hex(16)}
CASTOR_DATA_KEY={secrets.token_hex(32)}
CASTOR_DEFAULT_ADMIN_PASSWORD={secrets.token_hex(12)}
POSTGRES_DB=castor_{sql_id}
POSTGRES_USER=castor_{sql_id}
POSTGRES_PASSWORD={secrets.token_hex(24)}
REDIS_PASSWORD={redis_password}
S3_BUCKET=castor-{instance_id}
S3_ACCESS_KEY=castor-{instance_id}
S3_SECRET_KEY={secrets.token_hex(24)}
CASTOR_DB_HOST=postgres
CASTOR_REDIS_ADDR=redis:6379
CASTOR_S3_ENDPOINT=rustfs:9000
''')
    print(target)


class Instance:
    def __init__(self, env_file):
        self.env_file = Path(env_file)
        if not self.env_file.is_file():
            raise tooling.Failure(f'missing {self.env_file}')
        shared = shared_env_file()
        if not shared.is_file():
            raise tooling.Failure(f'missing {shared}')
        self.id = self.require('CASTOR_INSTANCE_ID', INSTANCE_ID_RE)
        self.db_name = self.require('POSTGRES_DB', r'[a-z_][a-z0-9_]{0,62}')
        self.db_user = self.require('POSTGRES_USER', r'[a-z_][a-z0-9_]{0,62}')
        self.bucket = self.require('S3_BUCKET', r'[a-z0-9][a-z0-9-]{1,61}[a-z0-9]')
        self.s3_user = self.require('S3_ACCESS_KEY', r'[a-z0-9][a-z0-9-]{2,62}')
        self.s3_endpoint = self.require('CASTOR_S3_ENDPOINT', r'[a-z0-9.-]+:[0-9]+')
        self.network = tooling.env_get(self.env_file, 'SHARED_NETWORK') or 'castor-shared'
        directory = str(compose_dir())
        self.shared = ['docker', 'compose', '--project-directory', directory, '--env-file', str(shared),
                       '-f', str(compose_dir() / 'compose.infra.yaml'),
                       '-f', str(compose_dir() / 'compose.shared.yaml')]
        self.instance = ['docker', 'compose', '--project-directory', directory,
                         '--env-file', str(self.env_file),
                         '-f', str(compose_dir() / 'compose.yaml'),
                         '-f', str(compose_dir() / 'compose.instance.yaml')]

    def require(self, key, pattern):
        value = tooling.env_get(self.env_file, key)
        if not re.fullmatch(pattern, value):
            raise tooling.Failure(f'{self.env_file}: {key} is missing or malformed')
        return value

    def provision(self):
        # Role and database owned by the instance; other instances' roles cannot connect.
        sql = PROVISION_SQL.format(db_name=self.db_name, db_user=self.db_user,
                                   db_password=self.require('POSTGRES_PASSWORD', SECRET_RE))
        tooling.run(self.shared + ['exec', '-T', 'postgres', 'sh', '-ec',
                                   'psql -q -U "$POSTGRES_USER" -d postgres'], input=sql.encode())
        shared = shared_env_file()
        root = f'{tooling.env_get(shared, "S3_ACCESS_KEY")} {tooling.env_get(shared, "S3_SECRET_KEY")}\n'
        credentials = f'{self.bucket} {self.s3_user} {self.require("S3_SECRET_KEY", SECRET_RE)}\n'
        # rc does not ship in the RustFS image, so provisioning runs in its own container on
        # the shared network; the storage administrator credentials come from the shared env.
        self.rc(PROVISION_BUCKET, [self.s3_endpoint], root + credentials)
        print(f'provisioned {self.id}: database {self.db_name}, bucket {self.bucket}')

    def rc(self, script, args, stdin, mount=None):
        """Run rc on the shared network. HOME is writable for rc's alias config, which is why
        the script can `rc alias set` even when the container runs as the host user."""
        user = [f'--user={os.getuid()}:{os.getgid()}'] if hasattr(os, 'getuid') else []
        volume = ['-v', f'{mount}:/backup'] if mount else []
        tooling.run(['docker', 'run', '--rm', '-i', '--network', self.network, *user, *volume,
                     '--entrypoint', '/bin/sh', RC_IMAGE, '-ec',
                     'export HOME="$(mktemp -d)"; ' + script, 'sh', *args],
                    input=stdin.encode())

    def rc_bucket(self, snapshot, script):
        """Run rc against this instance's bucket with its own credentials; the snapshot is /backup."""
        credentials = f'{self.s3_user} {self.require("S3_SECRET_KEY", SECRET_RE)}\n'
        self.rc('IFS=" " read -r ACCESS SECRET; rc alias set s3 "http://$1" "$ACCESS" "$SECRET" >/dev/null; '
                + script, [self.s3_endpoint, self.bucket], credentials, mount=snapshot)

    def snapshot_root(self):
        return backup_root() / self.id

    def backup_or_restore(self, action, name=None, confirm=None):
        if action == 'backup':
            snapshot = self.snapshot_root() / f'snapshot-{tooling.timestamp()}'
            tooling.private_dir(snapshot, parents=True)
        else:
            if not re.fullmatch(SNAPSHOT_RE, name or ''):
                raise tooling.Failure('snapshot name: snapshot-YYYYmmdd_HHMMSS')
            snapshot = self.snapshot_root() / name
            dump = snapshot / 'database.dump'
            if not ((snapshot / 'complete').is_file() and dump.is_file() and dump.stat().st_size
                    and (snapshot / 'bucket').is_dir()):
                raise tooling.Failure(f'incomplete snapshot: {snapshot}', code=1)
            # Explicit operator acknowledgement; never infer restore consent.
            if confirm != f'{self.id}/{name}':
                raise tooling.Failure(f'--confirm {self.id}/{name}')
        # Fetch the helper before interrupting the instance; offline hosts preload it.
        if tooling.run(['docker', 'image', 'inspect', RC_IMAGE], stdout=tooling.DEVNULL,
                       stderr=tooling.DEVNULL, check=False):
            tooling.run(['docker', 'pull', RC_IMAGE], stdout=tooling.DEVNULL)
        # Only this instance's API stops: the database and bucket must not change while they
        # are copied. Other instances keep serving.
        api_running = tooling.capture(self.instance + ['ps', '--status', 'running', '-q', 'castor-api'])
        succeeded = False
        if api_running:
            tooling.run(self.instance + ['stop', 'castor-api'])
        try:
            if action == 'backup':
                with tooling.private_file(snapshot / 'database.dump', 'wb') as dump:
                    tooling.run(self.shared + ['exec', '-T', 'postgres', 'sh', '-ec',
                                               'pg_dump -U "$POSTGRES_USER" -Fc -d "$1"', 'sh', self.db_name],
                                stdout=dump)
                (snapshot / 'bucket').mkdir(mode=0o700)
                self.rc_bucket(snapshot, 'rc mirror --quiet "s3/$2" /backup/bucket >/dev/null')
                shutil.copyfile(self.env_file, snapshot / 'instance.env')
                os.chmod(snapshot / 'instance.env', 0o600)
                (snapshot / 'complete').touch()
                print(snapshot)
            else:
                with open(snapshot / 'database.dump', 'rb') as dump:
                    tooling.run(self.shared + ['exec', '-T', 'postgres', 'sh', '-ec',
                                               'pg_restore -U "$POSTGRES_USER" -d "$1" --role="$2" --no-owner '
                                               '--clean --if-exists --single-transaction',
                                               'sh', self.db_name, self.db_user], stdin=dump)
                self.rc_bucket(snapshot, 'rc mirror --quiet --overwrite --remove /backup/bucket "s3/$2" >/dev/null')
            succeeded = True
        finally:
            # A failed restore stays stopped so partially restored data is never served.
            if api_running and (succeeded or action == 'backup'):
                tooling.run(self.instance + ['start', '--wait', '--wait-timeout', '180', 'castor-api'])


def instance_env_files():
    """Every instance env file, sorted by instance id."""
    directory = compose_dir() / 'instances'
    return sorted(directory.glob('*.env')) if directory.is_dir() else []


def status():
    files = instance_env_files()
    if not files:
        print('no instances (create one with: compose-instance.py new <id> <port>)')
        return
    for env_file in files:
        instance = Instance(env_file)
        port = tooling.env_get(env_file, 'HTTP_PORT') or '-'
        running = tooling.capture(instance.instance + ['ps', '--status', 'running', '-q', 'castor-api'])
        print(f'{instance.id}\t{port}\t{"running" if running else "stopped"}')


ALL_ACTIONS = ('up', 'pull', 'rollback', 'backup')


def run_all(action, keep_going):
    """Run one action on every instance; returns the exit code."""
    if action not in ALL_ACTIONS:
        raise tooling.Failure(f'all: {"|".join(ALL_ACTIONS)} [--keep-going]')
    files = instance_env_files()
    if not files:
        raise tooling.Failure('no instances in deploy/compose/instances/')
    results = []
    for env_file in files:
        name = env_file.stem
        print(f'==> {action} {name}', flush=True)
        try:
            if action == 'backup':
                Instance(env_file).backup_or_restore('backup')
                code = 0
            else:
                code = tooling.load_script('deploy-compose').main([action, 'instance', str(env_file)]) or 0
        except tooling.Failure as failure:
            if str(failure):
                print(failure, file=sys.stderr)
            code = failure.code or 1
        except subprocess.CalledProcessError as error:
            code = error.returncode or 1
        results.append((name, code))
        if code and not keep_going:
            break
    done = {name for name, _ in results}
    for name, code in results:
        print(f'{"ok" if code == 0 else "FAILED"}\t{name}')
    for env_file in files:
        if env_file.stem not in done:
            print(f'skipped\t{env_file.stem}')
    return 1 if any(code for _, code in results) else 0


def main(argv):
    action = tooling.arg(argv, 0, 'new|provision|backup|list|restore|status|all')
    if action == 'new':
        return new(tooling.arg(argv, 1, 'instance id'), tooling.arg(argv, 2, 'http port'))
    if action == 'status':
        return status()
    if action == 'all':
        extra = argv[2:]
        if extra not in ([], ['--keep-going']):
            raise tooling.Failure(f'all: {"|".join(ALL_ACTIONS)} [--keep-going]')
        return run_all(tooling.arg(argv, 1, "|".join(ALL_ACTIONS)), bool(extra))
    if action not in ('provision', 'backup', 'list', 'restore'):
        raise tooling.Failure(__doc__)
    instance = Instance(tooling.arg(argv, 1, 'instance env file'))
    if action == 'provision':
        instance.provision()
    elif action == 'list':
        for snapshot in tooling.snapshots(instance.snapshot_root()):
            print(snapshot)
    elif action == 'backup':
        instance.backup_or_restore('backup')
    else:
        name = tooling.arg(argv, 2, 'snapshot name')
        confirm = argv[4] if len(argv) == 5 and argv[3] == '--confirm' else None
        instance.backup_or_restore('restore', name, confirm)


if __name__ == '__main__':
    sys.exit(tooling.cli(main, sys.argv[1:]))
