#!/usr/bin/env python3
"""Kubernetes initialization and deployment.

Render: deploy-k8s.py render <target> [output-file]
Deploy: deploy-k8s.py <apply|rollback> <target> <kube-context>
New instance: deploy-k8s.py new <instance-id> <domain>
Every instance: deploy-k8s.py <apply-all|rollback-all> <kube-context> [--keep-going]

<target> is staging, production, or an instance id created by `new` (one tenant per
instance: deploy/k8s/instances/<id>/, namespace castor-<id>). The *-all commands walk the
instances in id order and stop at the first failure; --keep-going continues and still
exits non-zero.
"""
from datetime import datetime, timezone
import os
from pathlib import Path
import secrets
import shutil
import subprocess
import sys
import re
import tempfile
import time

import _tooling as tooling


def check_env_file(path):
    """Refuse empty or malformed secrets before anything reaches the cluster."""
    for line in Path(path).read_text(encoding='utf-8').splitlines():
        line = line.rstrip('\r')
        if not line or line.startswith('#'):
            continue
        key, _, value = line.partition('=')
        if not value:
            raise tooling.Failure(key)
        if key == 'CASTOR_RSA_SECRET' and len(value) != 32:
            raise tooling.Failure(f'{key} must be exactly 32 characters')
        if key == 'CASTOR_DATA_KEY' and len(value) < 32:
            raise tooling.Failure(f'{key} must be at least 32 characters')
        if key == 'CASTOR_DEFAULT_ADMIN_PASSWORD' and len(value) < 8:
            raise tooling.Failure(f'{key} must be at least 8 characters')


ENVIRONMENTS = ('staging', 'production')
INSTANCE_ID_RE = r'[a-z0-9][a-z0-9-]{0,31}'
# Overlay copied by `new`; it refuses a template whose namespace, host or instance id it cannot find exactly.
TEMPLATE = 'production'
TEMPLATE_HOST = 'castor.example.com'
PRIVATE_FILES = ('secrets.env', 'bootstrap.env', 'api.config.toml')


def instances_dir():
    return tooling.ROOT / 'deploy/k8s/instances'


def instance_ids():
    directory = instances_dir()
    if not directory.is_dir():
        return []
    return sorted(p.name for p in directory.iterdir() if (p / 'kustomization.yaml').is_file())


def overlay_for(target):
    if target in ENVIRONMENTS:
        return tooling.ROOT / 'deploy/k8s/overlays' / target
    if re.fullmatch(INSTANCE_ID_RE, target) and (instances_dir() / target / 'kustomization.yaml').is_file():
        return instances_dir() / target
    raise tooling.Failure(f'unknown target {target!r}: staging, production, or an instance id from `new`')


def replace_once(text, old, new, what):
    if text.count(old) != 1:
        raise tooling.Failure(f'template overlay: expected exactly one {what}')
    return text.replace(old, new)


def new(instance_id, domain):
    """Create deploy/k8s/instances/<id>/ from the production overlay with fresh secrets."""
    if not re.fullmatch(INSTANCE_ID_RE, instance_id) or instance_id in ENVIRONMENTS:
        raise tooling.Failure("instance id: 1-32 lowercase letters, digits or '-' (not staging/production)")
    if not re.fullmatch(r'[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+', domain):
        raise tooling.Failure('domain: a lowercase host name such as tenant-a.example.com')
    target = instances_dir() / instance_id
    if target.exists():
        raise tooling.Failure(f'{target} already exists')
    template = tooling.ROOT / 'deploy/k8s/overlays' / TEMPLATE
    namespace = f'castor-{instance_id}'
    kustomization = (template / 'kustomization.yaml').read_text(encoding='utf-8')
    kustomization = replace_once(kustomization, f'namespace: castor-{TEMPLATE}\n', f'namespace: {namespace}\n', 'namespace')
    if kustomization.count(f'value: {TEMPLATE_HOST}\n') != 2:
        raise tooling.Failure('template overlay: expected the host in the ingress rule and its TLS entry')
    kustomization = kustomization.replace(f'value: {TEMPLATE_HOST}\n', f'value: {domain}\n')
    kustomization = replace_once(kustomization, f'value: castor-{TEMPLATE}\n', f'value: {instance_id}\n', 'CASTOR_INSTANCE_ID')
    namespace_yaml = replace_once((template / 'namespace.yaml').read_text(encoding='utf-8'),
                                  f'name: castor-{TEMPLATE}\n', f'name: {namespace}\n', 'namespace name')
    tooling.private_dir(target, parents=True)
    # Everything else the template references (patches, env examples) is copied as is;
    # its real secrets and configuration are never copied.
    for source in sorted(template.iterdir()):
        if source.is_file() and source.name not in ('kustomization.yaml', 'namespace.yaml', *PRIVATE_FILES):
            shutil.copyfile(source, target / source.name)
    header = (f'# Castor instance "{instance_id}" (namespace {namespace}, https://{domain}).\n'
              '# Generated by scripts/deploy-k8s.py new; edit images and the ingress class as needed.\n')
    for name, content in (('kustomization.yaml', header + kustomization), ('namespace.yaml', namespace_yaml)):
        with open(target / name, 'w', encoding='utf-8', newline='\n') as output:
            output.write(content)
    # Secrets this instance owns are generated; external credentials stay empty so that
    # apply refuses to run until the operator fills them in.
    generated = {
        'CASTOR_JWT_KEY': secrets.token_hex(32),
        'CASTOR_RSA_SECRET': secrets.token_hex(16),
        'CASTOR_DATA_KEY': secrets.token_hex(32),
        'CASTOR_DEFAULT_ADMIN_PASSWORD': secrets.token_hex(12),
    }
    for name in ('secrets.env', 'bootstrap.env'):
        lines = []
        for line in (template / (name + '.example')).read_text(encoding='utf-8').splitlines():
            key = line.partition('=')[0]
            lines.append(f'{key}={generated[key]}' if key in generated else line)
        with tooling.private_file(target / name) as env:
            env.write('\n'.join(lines) + '\n')
    config = (tooling.ROOT / 'deploy/config/api.config.example.toml').read_text(encoding='utf-8')
    # The instance's host is known here; OIDC callbacks are built from it.
    config = config.replace('PublicURL = ""', f'PublicURL = "https://{domain}"', 1)
    with open(target / 'api.config.toml', 'w', encoding='utf-8', newline='\n') as output:
        output.write(config)
    print(target)


def run_all(action, context, keep_going):
    ids = instance_ids()
    if not ids:
        raise tooling.Failure('no instances in deploy/k8s/instances/ (create one with: deploy-k8s.py new)')
    results = []
    for instance_id in ids:
        print(f'==> {action} {instance_id}', flush=True)
        try:
            code = deploy(action, instance_id, context) or 0
        except tooling.Failure as failure:
            if str(failure):
                print(failure, file=sys.stderr)
            code = failure.code or 1
        except subprocess.CalledProcessError as error:
            code = error.returncode or 1
        results.append((instance_id, code))
        if code and not keep_going:
            break
    done = {instance_id for instance_id, _ in results}
    for instance_id, code in results:
        print(f'{"ok" if code == 0 else "FAILED"}\t{instance_id}')
    for instance_id in ids:
        if instance_id not in done:
            print(f'skipped\t{instance_id}')
    return 1 if any(code for _, code in results) else 0


def main(argv):
    action = tooling.arg(argv, 0, 'render|apply|rollback|new|apply-all|rollback-all')
    if action == 'new':
        return new(tooling.arg(argv, 1, 'instance id'), tooling.arg(argv, 2, 'domain'))
    if action in ('apply-all', 'rollback-all'):
        context = tooling.arg(argv, 1, 'explicit kube-context required')
        if argv[2:] not in ([], ['--keep-going']):
            raise tooling.Failure(__doc__)
        return run_all(action.removesuffix('-all'), context, bool(argv[2:]))
    target = tooling.arg(argv, 1, 'staging|production|<instance-id>')
    overlay = overlay_for(target)
    if action == 'render':
        if len(argv) < 3:
            return tooling.run(['kubectl', 'kustomize', str(overlay)])
        # Rendered manifests contain Secret data: write them owner-only, replacing any old copy.
        output_path = Path(argv[2])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.unlink(missing_ok=True)
        with tooling.private_file(output_path, 'wb') as output:
            return tooling.run(['kubectl', 'kustomize', str(overlay)], stdout=output)
    if action not in ('apply', 'rollback'):
        raise tooling.Failure(__doc__)
    return deploy(action, target, tooling.arg(argv, 2, 'explicit kube-context required'))


def deploy(action, target, context):
    overlay = overlay_for(target)
    kubectl = ['kubectl', '--context', context]
    namespace = f'castor-{target}'

    # Render once so configuration and images cannot drift between phases.
    descriptor, manifest = tempfile.mkstemp(prefix='castor-', suffix='.yaml')
    locked = False
    try:
        with os.fdopen(descriptor, 'wb') as output:
            tooling.run(['kubectl', 'kustomize', str(overlay)], stdout=output)
        if 'REPLACE_WITH_RELEASE' in Path(manifest).read_text(encoding='utf-8'):
            raise tooling.Failure('replace every REPLACE_WITH_RELEASE placeholder in the overlay')
        for name in ('secrets.env', 'bootstrap.env'):
            check_env_file(overlay / name)

        tooling.run(kubectl + ['apply', '-f', manifest, '-l', 'castor.io/phase=namespace'])
        created = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
        tooling.run(kubectl + ['-n', namespace, 'create', 'configmap', 'castor-release-lock',
                               f'--from-literal=created-at={created}'])
        locked = True
        tooling.run(kubectl + ['apply', '-f', manifest, '-l', 'castor.io/phase=configuration'])
        if action == 'apply':
            job = f'castor-init-{int(time.time())}-{secrets.randbelow(32768)}'
            tooling.run(kubectl + ['-n', namespace, 'create', 'job', job, '--from=cronjob/castor-init-db'])
            if tooling.run(kubectl + ['-n', namespace, 'wait', '--for=condition=complete',
                                      '--timeout=700s', f'job/{job}'], check=False):
                tooling.run(kubectl + ['-n', namespace, 'logs', f'job/{job}', '--all-containers=true'],
                            check=False)
                raise tooling.Failure(code=1)
        tooling.run(kubectl + ['apply', '-f', manifest, '-l', 'castor.io/phase=application'])
        for deployment in ('castor-api', 'castor-web'):
            tooling.run(kubectl + ['-n', namespace, 'rollout', 'status', f'deployment/{deployment}',
                                   '--timeout=300s'])
    finally:
        os.unlink(manifest)
        if locked:
            tooling.run(kubectl + ['-n', namespace, 'delete', 'configmap', 'castor-release-lock',
                                   '--ignore-not-found'], check=False)


if __name__ == '__main__':
    sys.exit(tooling.cli(main, sys.argv[1:]))
